[workspace]
resolver = "2"
members = [
    "crates/wgpu_solver_backend",
    "crates/wgpu_solver_backend_cli",
    "crates/wgpu_solver_backend_convert_cli",
]

[workspace.dependencies]
futures = "0.3.31"
wgpu = "28.0.0"
clap = "4.5.53"
serde = "1.0.228"
serde_json = "1.0.148"
