[package]
name = "wgpu_solver_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
thiserror = "2.0.17"
bytemuck = { version = "1.24.0", features = ["derive"] }
futures.workspace = true
